name: data_chatbox
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.6.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.19.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
